### ISSUE TITLE
Feedback HTML & CSS overzicht code

### ISSUE THREAD

**Issue by FatimaZelay** [DivaniNL/look-and-feel-corporate-identity#32]
Probeer de code overzichtelijker te maken door wat witte ruimte te creeren en comments te plaatsen.

**Comment by DivaniNL** [comment]
Bijvoorbeeld comments toevoegen bij de donation box in css

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/look-and-feel-corporate-identity/commit/158a377c57c48071486a806a510b092653070201
https://github.com/DivaniNL/look-and-feel-corporate-identity/commit/4d1f85bf802729ee26d3e4b373508b3899ff80e0
Gedaan. De code is nu beter te lezen
