### ISSUE TITLE
Font size (styleguide)

### ISSUE THREAD

**Issue by Matthijs217** [DivaniNL/look-and-feel-corporate-identity#33]
https://github.com/DivaniNL/look-and-feel-corporate-identity/blob/825e45f8535571f59dbf8617c54814c565a87854/style/home.css#L176

je gebruikt hier je eigen font-size, maar je hebt je font-size voor je "p" al aangegeven in de gedeelde stylesheet.

**Comment by DivaniNL** [comment]
Dit is gedaan. Zie commit:
https://github.com/DivaniNL/look-and-feel-corporate-identity/commit/fb9498bac0ae6ad3914e700a2d1cb8bca4dcdea3
